---
title: "Robust GFA simulation"
author: "Katie Forthman"
date: "4/29/2020"
output: pdf_document
---

```{r}
# ---- Load packages ----

## Required packages
library(GFA)
library(knitr)
library(gplots)
library(ggplot2)
library(foreach)
library(DMwR)
library(dplyr)
## Load optmThrGFA
library(devtools)
install_github("kforthman/optmThrGFA")
library(optmThrGFA)


# ---- Set GFA Options ----
opts <- getDefaultOpts()
opts$convergenceCheck <- T
# opts$verbose <- 0 # Set to 0 if you do not 
# want to print results of each gfa replicate


# ---- Set file paths ----
folder <- "res_groupMislabeled" # The folder where you want to put the results
if(!file.exists(folder)){dir.create(folder)} # Will create the results folder if it does not exist
data_dir <- "data" # The folder that contains your raw data
match.filename <- paste0(folder, "/match_orig.rda")

```

```{r}
load(match.filename)
opt.par.filename <- paste0(folder, "/opt.par.rda")
load(opt.par.filename)
message(paste0("The min. MSE = ", round(opt.par$mse.min, 3)))
message(paste0("The 1-SE MSE threshold = ", round(opt.par$mseThr, 3)))
message(paste0("min. MSE criterion gives ", opt.par$Krobust.min, " matched factors"))
message(paste0("1-SE MSE criterion gives ", opt.par$Krobust.1se, " matched factors"))
```

```{r}
Kgrids.filename <- paste0(folder, "/Kgrids.rda")
load(Kgrids.filename)
Kgrids
```

```{r}
optParams.filename <- paste0(folder, "/optParams.rda")
load(optParams.filename)
optParams
```

```{r}
rep.fac.effects.filename <- paste0(folder, "/rep.fac.effects.rda")
load(rep.fac.effects.filename)
summary(rep.fac.effects)

kable(rep.fac.effects, digits=2)
```

```{r}
varexp.filename <- paste0(folder, "/varexp.rda")
load(varexp.filename)

ve.summ <- varexp$ve.summ
ve.summ <- ve.summ[order(ve.summ$Component),]
ggplot(ve.summ, aes(x=1:nrow(ve.summ), y=Mean, ymin=Mean-SE, ymax=Mean+SE)) + 
    geom_pointrange() +
    xlab('Robust factors') + ylab('Percent variance explained') + ggtitle("Varaince explained")
```

Matching index matrix
```{r}
varexp$indices
```

```{r}
ve.summ <- varexp$ve.by.block.comp
ve.summ <- data.frame(ve.summ)

tmp <- paste0(round(varexp$ve.by.block$Mean, 1), ' +/- ', round(varexp$ve.by.block$SE, 1))
block.labs <- c("Block_1" = tmp[1], "Block_2" = tmp[2], "Block_3" = tmp[3], "Block_4" = tmp[4])
    
ggplot(ve.summ, aes(x=Component, y=Mean, ymin=Mean-SE, ymax=Mean+SE, color=Block)) +
  geom_pointrange() +
  facet_wrap(~ Block, labeller = labeller(Block = block.labs)) +
  xlab('Robust factors') + ylab('Variance explained (%)') +
  ggtitle("% variance explained by robust factors in each block")
```

```{r}
robust.xw.filename <- paste0(folder, "/robust.xw.rda")
load(robust.xw.filename)
load(paste0(folder, "/block.names.rda"))
load(paste0(folder, "/varIdx.by.block.rda"))
load(paste0(folder, "/block4vars.rda"))

gfa_heatmap(
  robW = robust.xw,
  block.names=block.names,
  varIdx.by.block=varIdx.by.block,
  conf.level=0.95,
  heatmap.rep=F,
  factor.order=1:35)

```

```{r}
GFAfactorlabels <- c("rGFA")
mytitles <- paste0(GFAfactorlabels, varexp$ve.summ$Component, ': ', round(varexp$ve.summ$Mean, 1), '% Var.')
w.summ <- robust.xw$w.ci.med
names(w.summ)[names(w.summ)=="Block"] <- "GFAgroups"
names(w.summ)[names(w.summ)=="var.lab"] <- "GFAvarlabs"
for (f in 1:35){
  print(
    Circbar(mydata = w.summ[w.summ$Component==varexp$ve.summ$Component[f],], 
            ebar = 2, 
            graphtitle = mytitles[f], 
            textlabel = 2, 
            minx = -0.5, 
            maxx = 0.5
            )
    )
}
```